import random

gameNumber = random.randint(0,9)
print(gameNumber)

userInput = input("WELCOME TO THE GUESSING GAME! GUESS A NUMBER FROM 1-9 IF YOU GET IT RIGHT YOU GET A PRIZE!!!!")

if userInput == gameNumber:
    print("DING DING DING DING DING DING DING DING DIGN DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN  DING DING DING DING DING DING DING DING DIGN ")

else:
    print("Sorry you got it wrong")